import os
from tensorflow.keras.preprocessing.image import ImageDataGenerator

import matplotlib.pyplot as plt


def plot_augmented_images(image_iterator, plot=False):
    """
    Plots 4 images generated by an object of the ImageDataGenerator class.
    """
    # Plot the images given by the iterator
    fig, rows = plt.subplots(nrows=1, ncols=4, figsize=(18, 18))
    for row in rows:
        image = image_iterator.next()[0].astype('int')
        row.imshow(image)
        row.axis('on')
    if plot:
        plt.show()
    plt.close('all')


def imageAugmentor(images, save_to_dir, plot=False):
    # Rotation
    data_generator = ImageDataGenerator(rotation_range=180)
    data_generator.fit(images)
    image_iterator = data_generator.flow(images,
                                         save_to_dir=save_to_dir,
                                         save_prefix='aug',
                                         save_format='jpg')

    plot_augmented_images(image_iterator, plot=plot)

    # Width shift
    data_generator = ImageDataGenerator(featurewise_center=False, width_shift_range=0.65)
    data_generator.fit(images)
    image_iterator = data_generator.flow(images,
                                         save_to_dir=save_to_dir,
                                         save_prefix='aug',
                                         save_format='jpg')

    plot_augmented_images(image_iterator, plot=plot)

    # Width shift
    data_generator = ImageDataGenerator(featurewise_center=False, width_shift_range=0.65)
    data_generator.fit(images)
    image_iterator = data_generator.flow(images,
                                         save_to_dir=save_to_dir,
                                         save_prefix='aug',
                                         save_format='jpg')

    plot_augmented_images(image_iterator, plot=plot)

    # Vertical Flip
    data_generator = ImageDataGenerator(vertical_flip=True, zoom_range=[0.2, 0.9], width_shift_range=0.2)
    data_generator.fit(images)
    image_iterator = data_generator.flow(images,
                                         save_to_dir=save_to_dir,
                                         save_prefix='aug',
                                         save_format='jpg')

    plot_augmented_images(image_iterator, plot=plot)

    # Horizontal shift
    data_generator = ImageDataGenerator(horizontal_flip=True, zoom_range=[1, 1.5], width_shift_range=0.2)
    data_generator.fit(images)
    image_iterator = data_generator.flow(images,
                                         save_to_dir=save_to_dir,
                                         save_prefix='aug',
                                         save_format='jpg')

    plot_augmented_images(image_iterator, plot=plot)

    # Width shift
    data_generator = ImageDataGenerator(width_shift_range=[0.1, 0.5])
    data_generator.fit(images)
    image_iterator = data_generator.flow(images,
                                         save_to_dir=save_to_dir,
                                         save_prefix='aug',
                                         save_format='jpg')

    plot_augmented_images(image_iterator, plot=plot)

    # Zoom and rotate
    data_generator = ImageDataGenerator(zoom_range=[1, 2], rotation_range=260)
    data_generator.fit(images)
    image_iterator = data_generator.flow(images,
                                         save_to_dir=save_to_dir,
                                         save_prefix='aug',
                                         save_format='jpg')

    plot_augmented_images(image_iterator, plot=plot)


def perform_data_augmentation(data_path, plot=False):
    class_names = os.listdir(data_path)
    for class_name in class_names:
        image_names = os.listdir(os.path.join(data_path, class_name))
        print('Processing Images from class {} which contains {} samples'.format(class_name, len(image_names)))
        for image_name in image_names:
            print('Processing Image {}'.format(image_name))
            image_path = os.path.join(data_path, class_name, image_name)
            image = plt.imread(image_path)
            images = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
            imageAugmentor(images, save_to_dir=os.path.join(data_path, class_name), plot=plot)
